### ISSUE TITLE
这个程序从哪里跑起

### ISSUE THREAD

**Issue by 1014470807** [githubliruiyuan/HybridFlutter#1]

**Comment by githubliruiyuan** [comment]
1、目前只实现了Android版，需要使用Android Studio导入项目，路径如下图所示；
2、将main.dart中的_pageCode值改为“home”，如下图所示。
![](https://user-gold-cdn.xitu.io/2019/10/11/16db8b9afc9f6eac?w=1212&h=738&f=png&s=143747)
