### ISSUE TITLE
如何让invokeMethod能够同步执行 如require等语法 

### ISSUE THREAD

**Issue by fangkyi03** [githubliruiyuan/HybridFlutter#3]

**Comment by githubliruiyuan** [comment]
按我理解的两种异步invokeMethod

第一种：
async(callback(result){
// do something
})

第二种：
var result = await async()

你说的应该是第二种方式，同步执行，那就只能阻塞js线程

**Comment by fangkyi03** [comment]
是这样的 因为jscore对于require的不支持 所以 现在 我只能在jscore里面相当于是捕获他的参数 然后由我自己去加载对应的文件 然后处理完以后 在返回过去 但是现在 如果这个操作要在flutter里面去做的话 那么逻辑就是这样的 ios - flutter - ios 这个时候 ios并不会等待我的这个invokeMethod执行完以后才继续往下走 问题就是处在这里 因为是用一个callback来做的 并不是一个同步的操作

**Comment by githubliruiyuan** [comment]
一方面在ios里面invokeMethod要阻塞线程，等待执行完成再释放
在js端需要将callback对应的调用方法改成同步阻塞方式

**Comment by fangkyi03** [comment]
你在ios里面 用js加载另一个文件的时候 你肯定是需要当jscore执行到那个位置的时候 你预先去读取完那个文件并返回数据 然后继续往下执行 不然你那个require的文件从哪来
