### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by Owenli0202** [githubliruiyuan/HybridFlutter#7]
你好，项目对flutter版本有要求吗？我现在用的是1.17.3版本，工程跑起来说需要开启androidX支持，如果我开启了，项目中用的是support包，又会有冲突。
报错信息如下：
This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.core:core:1.1.0, androidx.fragment:fragment:1.1.0, androidx.versionedparcelable:versionedparcelable:1.1.0, androidx.lifecycle:lifecycle-common:2.2.0, androidx.lifecycle:lifecycle-common-java8:2.2.0, androidx.customview:customview:1.0.0, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.lifecycle:lifecycle-viewmodel:2.1.0, androidx.loader:loader:1.0.0, androidx.lifecycle:lifecycle-livedata-core:2.0.0, androidx.activity:activity:1.0.0, androidx.collection:collection:1.1.0, androidx.viewpager:viewpager:1.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.arch.core:core-common:2.1.0, androidx.savedstate:savedstate:1.0.0, androidx.annotation:annotation:1.1.0, androidx.lifecycle:lifecycle-runtime:2.2.0

**Comment by githubliruiyuan** [comment]
flutter sdk 版本不同导致，已兼容最新版本flutter sdk
